adrih1/deflavour

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/policies/application_policy.rb, config/environments/development.rb, config/initializers/geocoder.rb, config/storage.yml, db/migrate/20220829131146_create_active_storage_tables.active_storage.rb, db/schema.rb
• Devise (authentification)
• Geocoder (MapBox)
• Cloudinary
• Pundit 
• Pg-Search
=> App - Set-Up

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_navbar.scss, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb
• Navbar first template 
• + buttons base
=> First Navbar Template

app/assets/stylesheets/components/_index.scss, app/views/layouts/application.html.erb
=> Heroku Fix

Gemfile.lock, app/controllers/spirits_controller.rb, db/seeds.rb
Add 6 spirits manually in the seed
Small fix in the spirit controller
=> Add 6 spirits in the seed and other small fix

db/migrate/20220830083951_add_image_url_to_spirits.rb, db/schema.rb, db/seeds.rb
=> seed almsost done

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_index.scss, app/views/pages/home.html.erb, app/views/shared/_spirit-card.html.erb
=> Spirit Card

app/controllers/spirits_controller.rb, app/policies/spirit_policy.rb, db/migrate/20220830100340_add_admin_to_users.rb, db/schema.rb, test/policies/spirit_policy_test.rb
• Pundit Policy
• Added Admin Column to User
• Check if record.user == user.admin? works
=> Pundit & Policy

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/views/layouts/application.html.erb, app/views/shared/_footer.html.erb, db/schema.rb
• Footer Front V1
• Back need to be done
=> Footer V1 Front

app/assets/stylesheets/components/_card.scss, app/controllers/spirits_controller.rb, app/policies/spirit_policy.rb, app/views/layouts/application.html.erb, app/views/shared/_navbar.html.erb, app/views/spirits/index.html.erb, db/schema.rb
• Index Spirits 
• Pundit Correction
=> Index Spirits + Pundit

app/views/shared/_footer.html.erb
=> Target Blank - New Window Open

app/assets/stylesheets/components/_card.scss
=> Small Fix on details

app/views/pages/home.html.erb, app/views/shared/_login.html.erb, app/views/shared/_signup.html.erb, config/routes.rb, db/schema.rb
=> add device on home page

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_devise-forms.scss, app/assets/stylesheets/components/_index.scss, app/views/pages/home.html.erb, app/views/shared/_login.html.erb, app/views/shared/_signup.html.erb
• Basic front done for devise forms
=> Forms Log In and Sign In Basic Front

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_devise-forms.scss
=> Log In and Sign Up Form Done

app/controllers/spirits_controller.rb, app/javascript/controllers/index.js, app/views/pages/home.html.erb
• Conditonnal for home page after logged In began
=> Home If Logged in

db/seeds.rb
• Deleting .strip for Heroku to work
=> Deleting .strip for Heroku

app/controllers/pages_controller.rb, db/seeds.rb
=> Commented Antoine's and Paul's test

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/config/_fonts.scss, app/controllers/pages_controller.rb, app/views/pages/dashboard.html.erb, app/views/pages/home.html.erb, app/views/shared/_login.html.erb, app/views/shared/_navbar.html.erb, app/views/shared/_signup.html.erb, app/views/spirits/index.html.erb
Change colors
Add font
Create Dashboard page
=> change colors and created dashboard page

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_button.scss, app/controllers/experiences_controller.rb, app/javascript/controllers/index.js, app/javascript/controllers/tom_select_controller.js, app/models/spirit.rb, app/models/user.rb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, config/routes.rb, db/migrate/20220831143925_add_rating_to_experiences.rb, db/schema.rb, package.json, test/controllers/experiences_controller_test.rb
=> Autocomplte experiences save

app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_show.scss, app/controllers/spirits_controller.rb, app/javascript/controllers/index.js, app/javascript/controllers/map_controller.js, app/models/spirit.rb, app/views/pages/dashboard.html.erb, app/views/spirits/index.html.erb, app/views/spirits/show.html.erb, db/migrate/20220831133856_add_coordinates_to_spirits.rb, db/schema.rb, db/seeds.rb
Add show
Did front on the show
Add map
=> front for show

app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb, app/views/spirits/index.html.erb, db/schema.rb
• Margin Top on container in index Spirits 
• Navbar : Sign Out and Search nav-link class added / Alignement on same line
=> Navbar / Spirits Index

app/controllers/spirits_controller.rb, app/javascript/controllers/index.js, app/javascript/controllers/search_toggle_controller.js, app/models/spirit.rb, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb
Add link to home cards
Add pg search
Initiated JS controllers for toggle search bar
=> add link to home cards

app/views/pages/home.html.erb, app/views/spirits/index.html.erb
Add links
Add feature to marketplace (count, if, etc...)
=> add features to marketplace

app/assets/stylesheets/components/_footer.scss, app/views/shared/_footer.html.erb
=> Footer-Finish

app/views/pages/home.html.erb
=> Banner Fixed

app/views/pages/home.html.erb
• Closed div earlier for better front
=> Banner closed div earlier

app/javascript/controllers/index.js, app/javascript/controllers/search_toggle_controller.js, app/views/pages/dashboard.html.erb, app/views/pages/home.html.erb
Layout for Dashboard (front)
Links
=> front layout for dashboard

app/controllers/recommendations_controller.rb, app/controllers/spirits_controller.rb, app/models/alcool_profile.rb, app/models/recommendation.rb, app/models/spirit.rb, app/models/user.rb, app/policies/spirit_policy.rb, app/views/pages/dashboard.html.erb, app/views/pages/home.html.erb, app/views/recommendations/index.html.erb, app/views/shared/_dashboard_mini.html.erb, config/routes.rb, db/migrate/20220831084310_add_columns_to_users.rb, db/migrate/20220901101425_create_recommendations.rb, db/migrate/20220901102229_add_column_to_alcool_profile.rb, db/schema.rb, test/controllers/recommendations_controller_test.rb, test/models/recommendation_test.rb
Add recommendation model/controller/route (need to check the pundit)
Add columns to alcool_profiles
=> add recommendations model

db/migrate/20220831100026_remove_fielexperiences_from_users.rb, db/migrate/20220901102229_add_column_to_alcool_profile.rb, db/schema.rb
=> migrate fix

app/controllers/recommendations_controller.rb, app/policies/recommendation_policy.rb, test/policies/recommendations_policy_test.rb
=> pundit reco

app/views/recommendations/index.html.erb
=> front reco

app/views/pages/home.html.erb
• Changed If relation to display "Voir mon profil" if passsed exeperiences
=> Changed if relation

db/seeds.rb
• Seed corrections
• Markers for Mapbox
=>  Seed Modif + Markers Mapbox

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_circle.scss, app/assets/stylesheets/components/_index.scss, app/views/recommendations/index.html.erb
=> recommendation view

app/controllers/application_controller.rb, app/views/pages/home.html.erb
Fix the routes with the correct path and user journey.
=> routes revamp

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/pages/_maindashboard.scss, app/views/pages/maindashboard.html.erb
Front of the main dashboard done
=> Main Dashboard Front End Done

app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb
• Voir mon profil button in the navbar 
• Créer des expérience button front-end done (need to connect with back end)
=> Front End Home and Navbar

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_modal.scss, app/controllers/orders_controller.rb, app/views/recommendations/index.html.erb, config/routes.rb
=> modal payment

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_experience-form.scss, app/views/pages/home.html.erb, app/views/shared/_experience_form.html.erb
=> Experience Form CHanges

app/views/pages/home.html.erb
=> Current User

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_devise-forms.scss, app/assets/stylesheets/components/_experience-form.scss, app/assets/stylesheets/components/_modal.scss, app/assets/stylesheets/pages/_dashboard.scss, app/controllers/pages_controller.rb, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb, app/views/spirits/index.html.erb
• Experience Form : "Générer mon profil aromatique" décalé à droite  et hover rectifié
• Icon supprimer expérience background supprimé / Nouvelle couleur
• Modale Log In revu
• Spirits Index : Titre et count alignés
=> Front End Changes

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/pages/_dashboard.scss, app/javascript/controllers/banner_change_controller.js, app/javascript/controllers/index.js, app/javascript/controllers/nested_form_controller.js, app/views/pages/home.html.erb
• Dynamic deployment of banner when button clicked
=> Experience Form - JS

Gemfile.lock, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_modal.scss, app/controllers/reviews_controller.rb, app/models/order.rb, app/models/review.rb, app/models/spirit.rb, app/models/user.rb, app/views/pages/maindashboard.html.erb, app/views/shared/_modal-reviews.html.erb, config/routes.rb, db/migrate/20220905084244_modify_columns_reviews.rb, db/migrate/20220905085221_add_reference_reviews.rb, db/schema.rb
=> add reviews

Gemfile.lock, app/assets/stylesheets/components/_modal.scss
=> Parantheses fix

app/assets/stylesheets/components/_card.scss, app/views/recommendations/index.html.erb
=> % align on bottom of cards

app/assets/stylesheets/components/_devise-forms.scss, app/javascript/controllers/devise_modal_controller.js, app/javascript/controllers/index.js, app/views/devise/sessions/new.html.erb, app/views/shared/_login.html.erb, app/views/shared/_signup.html.erb
JS on sign and log in to display only one of the form at a time
=> Dynamic Log and Sign Up

app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb
Added the code for the log in form to the registrations/new and sessions/new
=> JS Form Log IN

app/assets/stylesheets/components/_button.scss
Changed color of gold to hover to lighter blue
=> Changed color of hover buttons

app/views/pages/home.html.erb
Deleted the "if experiences.lenght > 0" so that create new experiences is always displayed and used with the JS
=> Conditonnal If changed

app/views/pages/dashboard.html.erb
=> Avatar Fixed + Margin on recommandation button

app/assets/stylesheets/components/_modal.scss
=> Mon Panier Fron revu

app/assets/stylesheets/components/_banner.scss
Height of banner fixed at 500px so that it doesn't move when switching from log in to sign up
=> Better banner for log in and sign in

app/assets/stylesheets/components/_banner.scss
=> banner height was not a good idea

app/assets/stylesheets/components/_tabs.scss, app/views/pages/maindashboard.html.erb, app/views/shared/_mon_bar.html.erb, app/views/shared/_profil_par_alcool.html.erb
=> tabs display fix

app/assets/stylesheets/components/_carousel-loading-reco.scss, app/assets/stylesheets/components/_index.scss, app/javascript/controllers/index.js, app/javascript/controllers/reco_carousel_controller.js, app/views/pages/dashboard.html.erb
• JS animation before recommandations page with 3D rotating bottles
=> V1 - Animation Loading Screen for recommandations

app/javascript/controllers/index.js, app/views/pages/dashboard.html.erb
Ok, before for potential conflicts
=> Useless Lines on index JS

db/seeds.rb
Longer sleep in order not to get banned
=> Longer sleep by safety for Heroku

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_button.scss, app/views/pages/home.html.erb
=> Changes on front end of banner and buttons

app/assets/stylesheets/components/_footer.scss, app/views/pages/dashboard.html.erb
=> Footer Icon Fix + Franglais correction

app/helpers/meta_tags_helper.rb, config/initializers/default_meta.rb
=> Files didn't save

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/pages/_dashboard.scss, app/assets/stylesheets/pages/_show.scss, app/controllers/pages_controller.rb, app/views/pages/dashboard.html.erb
=> front dashboard fait

app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/components/_tabs.scss, app/views/pages/maindashboard.html.erb, app/views/shared/_profil_aromatique.html.erb
=> main aroma front

app/javascript/controllers/banner_change_controller.js, app/javascript/controllers/index.js, app/javascript/controllers/loader_controller.js, app/views/pages/home.html.erb
Loading aromatic profile after experiences submitted
=> Loading aromatic profile

app/assets/stylesheets/components/_button.scss, app/views/pages/home.html.erb, app/views/shared/_experience_form.html.erb
=> small changes on buttons

db/seeds.rb
=> Sleep 30 seconds

config/meta.yml
=> New OG Image

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_reco.scss, app/views/recommendations/index.html.erb
=> reco front

db/seeds.rb
=> Seed from pages 8 to 14

db/seeds.rb
=> Seed 10-14

config/environments/production.rb
=> HTTPS setup good

db/seeds.rb
=> Seed 11-16

db/seeds.rb
=> Seed 13-16

db/seeds.rb
=> Seed 17-21

db/seeds.rb
=> Seed 19 to 22
